const aiKeywords = [
  "affordable global internships",
  "global internship opportunities 2023",
  "best global internship programs",
  "remote global internship positions",
  "global internship programs for students",
  "paid global internships abroad",
  "how to find global internships",
  "global internships for college students",
  "international internship opportunities",
  "top global internship companies",
  "global internship application tips",
  "global internship experience benefits",
  "global internship programs with housing",
  "virtual global internships for students",
  "global internships for recent graduates",
  "global internship opportunities for engineers",
  "global internship search websites",
  "global internships in marketing",
  "global internship programs in finance",
  "global internships for business majors",
  "how to apply for global internships",
  "global internships in non-profits",
  "short-term global internship programs",
  "global internship opportunities in tech",
  "global internships for environmental studies",
  "global internships in healthcare",
  "global internship placements for students",
  "global internships for language learners",
  "global internship programs with visa sponsorship",
  "global internships for art students",
  "global internship opportunities in education",
  "global internships for STEM students",
  "global internships in hospitality",
  "global internship opportunities for women",
  "global internships in social work",
  "global internships in research",
  "global internships for law students",
  "global internships for humanities majors",
  "global internship programs for high school students",
  "global internships in international relations",
  "global internships for tech startups",
  "global internships with cultural exchange",
  "global internships in digital marketing",
  "global internships for aspiring entrepreneurs",
  "global internships with travel opportunities","global internships with good accomodation"
];

return aiKeywords.map(keyword => ({
  json: {
    keyword: keyword,
    is_estimated: true
  }
}));